//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_UP07_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMP_UP07_Product()
        {
            this.IMP_UP07_BuyProduct = new HashSet<IMP_UP07_BuyProduct>();
            this.IMP_UP07_ImageProduct = new HashSet<IMP_UP07_ImageProduct>();
        }
    
        public int Id { get; set; }
        public int ManufacturerId { get; set; }
        public int ProductCategoryId { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public double Weigth { get; set; }
        public double Width { get; set; }
        public double Height { get; set; }
        public double Length { get; set; }
        public string MainImagePath { get; set; }
    
        public virtual IMP_UP07_Manufacturer IMP_UP07_Manufacturer { get; set; }
        public virtual IMP_UP07_ProductCategory IMP_UP07_ProductCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMP_UP07_BuyProduct> IMP_UP07_BuyProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMP_UP07_ImageProduct> IMP_UP07_ImageProduct { get; set; }
    }
}
