//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_UP07_Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMP_UP07_Client()
        {
            this.IMP_UP07_BuyProduct = new HashSet<IMP_UP07_BuyProduct>();
            this.IMP_UP07_ClientService = new HashSet<IMP_UP07_ClientService>();
        }
    
        public int Id { get; set; }
        public int GenderId { get; set; }
        public string LastName { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime BirthOfDay { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public System.DateTime VisitDate { get; set; }
        public string ImagePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMP_UP07_BuyProduct> IMP_UP07_BuyProduct { get; set; }
        public virtual IMP_UP07_Gender IMP_UP07_Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMP_UP07_ClientService> IMP_UP07_ClientService { get; set; }
    }
}
