//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_UP07_Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMP_UP07_Employee()
        {
            this.IMP_UP07_Service = new HashSet<IMP_UP07_Service>();
        }
    
        public int Id { get; set; }
        public int EmployeeCategoryId { get; set; }
        public int CodeDivision { get; set; }
        public int GenderId { get; set; }
        public string LastName { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public int SeriesPassport { get; set; }
        public int NumberPassport { get; set; }
        public decimal PaymentRatio { get; set; }
        public System.DateTime BirthOfDay { get; set; }
    
        public virtual IMP_UP07_Division IMP_UP07_Division { get; set; }
        public virtual IMP_UP07_EmployeeCategory IMP_UP07_EmployeeCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMP_UP07_Service> IMP_UP07_Service { get; set; }
    }
}
