//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IMP_UP07_BuyProduct> IMP_UP07_BuyProduct { get; set; }
        public virtual DbSet<IMP_UP07_Client> IMP_UP07_Client { get; set; }
        public virtual DbSet<IMP_UP07_ClientService> IMP_UP07_ClientService { get; set; }
        public virtual DbSet<IMP_UP07_Division> IMP_UP07_Division { get; set; }
        public virtual DbSet<IMP_UP07_Employee> IMP_UP07_Employee { get; set; }
        public virtual DbSet<IMP_UP07_EmployeeCategory> IMP_UP07_EmployeeCategory { get; set; }
        public virtual DbSet<IMP_UP07_Gender> IMP_UP07_Gender { get; set; }
        public virtual DbSet<IMP_UP07_ImageProduct> IMP_UP07_ImageProduct { get; set; }
        public virtual DbSet<IMP_UP07_ImageService> IMP_UP07_ImageService { get; set; }
        public virtual DbSet<IMP_UP07_Manufacturer> IMP_UP07_Manufacturer { get; set; }
        public virtual DbSet<IMP_UP07_Product> IMP_UP07_Product { get; set; }
        public virtual DbSet<IMP_UP07_ProductCategory> IMP_UP07_ProductCategory { get; set; }
        public virtual DbSet<IMP_UP07_Service> IMP_UP07_Service { get; set; }
    }
}
